### ISSUE TITLE
USER STORY: Log In

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#10]
As a **Site User** I can **log in** so that **I can comment on blog posts**

**Acceptance Criteria:**

1. Users can login with button on nav bar
2. User can see related content for their user level

**Tasks:**

- [ ] Create a super user
- [ ] Create a generic user
- [ ] Create login button
- [ ] If user is not registered, forward the user to the registration view
- [ ] Test superuser is shown as Admin User
- [ ] Test Site User login is shown as User
