### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#11]
As a **Site User / Admin User** I can **Log Out from my account** so that **only I can have access to my account**

**Acceptance Criteria:**

1. User's can log out when they feel they are done with their time on the site

**Tasks:**

- [ ] Create Log Out button which will replace the Log In button
- [ ] Create message informing user has logged out successfully
- [ ] Test user is logged out correctly
