### ISSUE TITLE
USER STORY: A User Can Comment on a Post

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#12]
As a **Site User / Admin User** I can **comment on posts** so that **I can provide my own opinion on the post**

**Acceptance Criteria:**

1. A user, once logged in can enter text into a comment text box and submit it to the post
2. A user, once the comment has been submitted can decide to edit / delete their comment

**Tasks:**

- [ ] Create comment model
- [ ] Create comment text box
- [ ] Create Edit / Delete function
