### ISSUE TITLE
USER STORY: Setup IDE Workspace

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#2]
As a **developer** I can **create my workspace on GitPod** so that **I can initialize my project**

**Acceptance Criteria:**

1. Set up workspace on GitPod

**Tasks:**

- [ ] Create workspace on GitPod
- [ ] Install Django
- [ ] Create requirements.txt
- [ ] Create project folder
- [ ] Create views and URLs
- [ ] Amend Allowed Hosts in Settings.py to be able to run server in browser
- [ ] Test all has been created correctly by running server in browser.
