### ISSUE TITLE
USER STORY: Create model schema

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#3]
As a **Developer** I can **create a model schema** so that **I can visualize how the databases will be organized and how the data on each database will be connected**

**Acceptance Criteria:**

1. ERD Models for each Database
2. Visualization of the relationship between the primary and foreign keys for each database

**Task:**

- [ ] Identify Primary and Foreign keys
- [ ] Show relationship between models 
- [ ] Create ERD's for each database model
- [ ] Add model schema in the README.md file
