### ISSUE TITLE
USER STORY: Create Databases

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#4]
As a **Developer** I can **use a Database** so that **I can create and adapt data within my Django project**

**Acceptance Criteria:**

1. Working databases with functionality based on the CRUD principle
2. Connect said databases to Heroku
3. Test to ensure the databases work correctly and have the correct fields

**Tasks:**

- [ ] Create Database
- [ ] Connect Database to code
- [ ] Create required fields in the databases
- [ ] Connect to Heroku
- [ ] Manually test to ensure the fields are correct on the databases and everything has been connected correctly
