### ISSUE TITLE
USER STORY: Deploy to Heroku

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#5]
As a **Developer** I can **deploy my project to Heroku** so that **I have my project deployed to a cloud, allowing me to manually test the project works in the terminal browser and as a Heroku app**

**Acceptance Criteria:**

1. In settings, set DEBUG = False
2. Ensure sensitive data is stored in env.py and env.py is in the .gitignore file

**Tasks:**

- [ ] Ensure project is deployed to Github first
- [ ] Create Heroku app
- [ ] Connect Heroku app to Github
- [ ] Update config vars in settings on Heroku
- [ ] Deploy branch manually
- [ ] Click on 'run app' to test if it has worked correctly.
