### ISSUE TITLE
USER STORY: Create Cigar Posts

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#6]
As an **Admin User** I can **Create cigar posts** so that **Site Users can view them and comment on them**

**Acceptance Criteria:**

1. As Admin, create posts which Site Users can view
2. Site Users won't be able to see what an Admin User can
3. Admin can edit and delete posts

**Tasks:**

- [ ] In models.py create the model for creating posts
- [ ] Add the model to admin.py
- [ ] Add edit / delete functions
- [ ] Test by creating a post, editing a post, deleting a post
