### ISSUE TITLE
USER STORY: Site Users can view posts

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#7]
As a **Site User** I can **view posts created by the Admin User** so that **I can comment on them**

**Acceptance Criteria:**

1. Site Users can see the posts created by Admin User

**Tasks:**

- [ ] Create templates folder
- [ ] Create html page
- [ ] Add url pattern into urls.py
- [ ] Import views 
- [ ] Test to ensure views are displayed to the browser
