### ISSUE TITLE
USER STORY: Write HTML/CSS

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#8]
As a **Developer** I can **write the HTML for the base.html and the CSS** so that **the Site User can view the website and the CSS will give the website style**

**Acceptance Criteria:**

1. Website needs to meet accessibility requirements
2. HTML code needs to be written in such a way that it will pass future tests
3. CSS needs to be written in such a way that it will pass future tests
4. Theme of the website needs to be consistent

**Tasks:**

- [ ] Create base.html
- [ ] Aria tags need to be added to images
- [ ] Ensure colours don't distract from the main information on the page
- [ ] Ensure no lorem ipsum text is used
