### ISSUE TITLE
USER STORY: Create User Account

### ISSUE THREAD

**Issue by James-PriestleyDev** [James-PriestleyDev/Cigar-Blog-PP4#9]
As a **Site User** I can **create my own user account** so that **I can comment on blog posts**

**Acceptance Criteria:**

1. Users will be able click a button to create their own user login for the site
2. Input fields will be pre-populated as a guide to what the site will register as a valid input
3. User will be able to log-in and create comments

**Tasks:**

- [ ] Create button for users to press to create their user account
- [ ] Create register model with relevant ERD
- [ ] Test creation of account is working correctly
